//API 1
GET http://localhost:3000/todos/
###

//SC-1
GET http://localhost:3000/todos/?status=TO%20DO
###

//SC-2
GET http://localhost:3000/todos/?priority=HIGH
###

//SC-3
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
###

//SC-4
GET http://localhost:3000/todos/?search_q=Buy
###

//SC-5
GET http://localhost:3000/todos/?category=WORK&status=DONE
###

//SC-6
GET http://localhost:3000/todos/?category=HOME
###

//SC-7
GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH
###

//API 2
GET http://localhost:3000/todos/5/
###

//API 3
GET http://localhost:3000/agenda/?date=2021-12-12
###

//API 4
POST httP://localhost:3000/todos/
Content-Type: application/json

{
 "id": 6,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-02-22"
}
###

//API 5
//SC-1
PUT http://localhost:3000/todos/6/
Content-Type: application/json

{ "status": "DONE" }
###

//SC-2
PUT http://localhost:3000/todos/6
Content-Type: application/json

{ "priority": "HIGH" }
###

//SC-3
PUT http://localhost:3000/todos/6
Content-Type: application/json

{
"todo": "Clean the garden"
}
###

//SC-4
PUT http://localhost:3000/todos/6
Content-Type: application/json

{ "category": "LEARNING" }
###

//SC-5
PUT http://localhost:3000/todos/6
Content-Type: application/json

{ "dueDate": "2021-01-12" }
###

//API 6
DELETE http://localhost:3000/todos/6/
###
